# Generated by Django 4.2.7 on 2026-01-10 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certifications', '0015_alter_modulo_options_alter_certification_ano_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='unique_link',
            field=models.CharField(blank=True, db_index=True, help_text='Você pode editar este link. Deixe em branco para gerar automaticamente.', max_length=100, null=True, unique=True, verbose_name='Link Único de Compartilhamento'),
        ),
    ]
